from winepredictor.data_utils import extract_features_and_target
from winepredictor.model_utils import run_knn_grid_search
from winepredictor.plot_utils import plot_correlation_heatmap, plot_quality_distribution
